package com.inovance.dam.core.entity.inovance;

import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * This class holds information about Inovance documents and metadata.
 *
 * @author Leon
 */
@Getter
@Setter
public class InovanceAsset {

    /**
     * Unique material ID generated by DAM
     */
    private String materialId;

    /**
     * Document version, corresponds to BTPRODUCTINFORMATION docversion
     */
    private String materialVersion;

    /**
     * Document size, corresponds to BTPRODUCTINFORMATION filesize (auto-generated)
     */
    private String documentSize;

    /**
     * Storage location, corresponds to BTPRODUCTINFORMATION doclocation (auto-generated)
     */
    private String storageLocation;

    /**
     * Download count (auto-generated by DAM)
     */
    private String downloadCount;

    /**
     * Material status, corresponds to BTPRODUCTINFORMATION docstate
     */
    private String materialStatus;

    /**
     * Query count (auto-generated by DAM)
     */
    private String queryCount;

    /**
     * Rating (auto-generated by DAM)
     */
    private String rating;

    /**
     * Document number, corresponds to BTPRODUCTINFORMATION docnumber
     */
    private String documentNumber;

    /**
     * Document name, corresponds to BTPRODUCTINFORMATION docname
     */
    private String documentName;

    /**
     * Security level, corresponds to BTPRODUCTINFORMATION secretdegree
     */
    private String securityLevel;

    /**
     * Application country
     */
    private String applicationCountry;

    /**
     * Language
     */
    private String language;

    /**
     * File format, corresponds to BTPRODUCTINFORMATION docclassification
     */
    private String fileFormat;

    /**
     * Document source (auto-generated by DAM)
     */
    private String documentSource;

    /**
     * Create time, corresponds to BTPRODUCTINFORMATION createtime
     */
    private Date createTime;

    /**
     * Release time (auto-generated by DAM)
     */
    private Date releaseTime;

    /**
     * Last modified time (auto-generated by DAM)
     */
    private Date lastModifiedTime;

    /**
     * Owner, corresponds to BTPRODUCTINFORMATION modifier
     */
    private String owner;

    /**
     * Code, corresponds to BTPRODUCTINFORMATION doctype
     */
    private String code;

    /**
     * Submitter (auto-generated by DAM)
     */
    private String submitter;

    /**
     * Approver (auto-generated by DAM)
     */
    private String approver;

    /**
     * Submit time (auto-generated by DAM)
     */
    private Date submitTime;

    /**
     * Approval time (auto-generated by DAM)
     */
    private Date approvalTime;

    /**
     * Offering ID, corresponds to PBI query sales catalog and association interface OFFERING_NO
     */
    private String offeringId;

    /**
     * Offering Chinese name, corresponds to PBI query sales catalog and association interface OFFERING_NAME
     */
    private String offeringChineseName;

    /**
     * Offering English name, corresponds to PBI query sales catalog and association interface OFFERING_ENGLISHNAME
     */
    private String offeringEnglishName;

    /**
     * Offering lifecycle, corresponds to PBI query sales catalog and association interface OFFERING_STATE
     */
    private String offeringLifecycle;

    /**
     * Product catalog, corresponds to PBI query sales catalog and association interface SALESCAT_NO_L0 to L4
     */
    private String productCatalog;

    /**
     * Project ID, corresponds to IPMS project information query PROJECTNUMBER
     */
    private String projectId;

    /**
     * Project name, corresponds to IPMS project information query PROJECTNAME
     */
    private String projectName;

    /**
     * Material category (large category), corresponds to mapping in PLM
     */
    private String materialCategory;

    /**
     * Material subcategory (small category)
     */
    private String materialSubcategory;

    /**
     * Project type, corresponds to IPMS project information query PROJECTTYPE
     */
    private String projectType;

    @Override
    public String toString() {
        return "Asset{" +
                "materialId='" + materialId + '\'' +
                ", materialVersion='" + materialVersion + '\'' +
                ", documentSize='" + documentSize + '\'' +
                ", storageLocation='" + storageLocation + '\'' +
                ", downloadCount='" + downloadCount + '\'' +
                ", materialStatus='" + materialStatus + '\'' +
                ", queryCount='" + queryCount + '\'' +
                ", rating='" + rating + '\'' +
                ", documentNumber='" + documentNumber + '\'' +
                ", documentName='" + documentName + '\'' +
                ", securityLevel='" + securityLevel + '\'' +
                ", applicationCountry='" + applicationCountry + '\'' +
                ", language='" + language + '\'' +
                ", fileFormat='" + fileFormat + '\'' +
                ", documentSource='" + documentSource + '\'' +
                ", createTime='" + createTime + '\'' +
                ", releaseTime='" + releaseTime + '\'' +
                ", lastModifiedTime='" + lastModifiedTime + '\'' +
                ", owner='" + owner + '\'' +
                ", code='" + code + '\'' +
                ", submitter='" + submitter + '\'' +
                ", approver='" + approver + '\'' +
                ", submitTime='" + submitTime + '\'' +
                ", approvalTime='" + approvalTime + '\'' +
                ", offeringId='" + offeringId + '\'' +
                ", offeringChineseName='" + offeringChineseName + '\'' +
                ", offeringEnglishName='" + offeringEnglishName + '\'' +
                ", offeringLifecycle='" + offeringLifecycle + '\'' +
                ", productCatalog='" + productCatalog + '\'' +
                ", projectId='" + projectId + '\'' +
                ", projectName='" + projectName + '\'' +
                ", materialCategory='" + materialCategory + '\'' +
                ", materialSubcategory='" + materialSubcategory + '\'' +
                ", projectType='" + projectType + '\'' +
                '}';
    }
}